source :rubygems

# Project requirements
gem 'rake'
gem 'haml'

# Padrino Edge
# %w(core gen helpers mailer admin).each do |gem|
  # gem 'padrino-' + gem, :path => '/src/padrino-framework/padrino-' + gem
# end

# Padrino
gem 'padrino'

gem 'thin'
